parameters:
    facebook_app_id: 681135752071347
    facebook_app_secret: 4660303bbe1e2c9b739c370dc5789df2
    google_app_id: 671676018360-51ltnrbvv8kort2ees2pgjfgir9l208b.apps.googleusercontent.com
    google_app_secret: SzgMWGdqGHD8_K4qbF3LtgRZ